### ISSUE TITLE
请问如何实现的路由跳转呢？

### ISSUE THREAD

**Issue by LHNfromTJ** [MuYunyun/reactSPA#17]
作者你好！我刚开始接触React，我看了下你的项目中路由是在routers.js中去配置的，但是里面只有首页与登录页的配置，那么点击侧边栏的时候让页面去跳转是如何实现的呢？这些是在哪里配置的呢？

**Comment by MuYunyun** [comment]
全局搜索 route 是能找到的，写在了 https://github.com/MuYunyun/reactSPA/blob/master/src/common/container/content.js 这，还未作分离
