### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by fengye12** [MuYunyun/reactSPA#18]
执行npm start 报错，什么原因呢？
F:\app\reactSPA-master\scripts\start.js:23
const {
      ^

SyntaxError: Unexpected token {

**Comment by MuYunyun** [comment]
依赖装了没

**Comment by fengye12** [comment]
npm install npm start 确实安装了

**Comment by MuYunyun** [comment]
应该是你个人环境的问题吧，我这边是正常的
