### ISSUE TITLE
完全不支持IE吗？

### ISSUE THREAD

**Issue by berserk5683** [MuYunyun/reactSPA#22]
IE11控制台都会报错“ 对象不支持“startsWith”属性或方法”，页面无法显示

**Comment by MuYunyun** [comment]
大部分属性IE11都是能支持的，有可能个别属性还未支持，未来会进行优化，谢谢你的意见

**Comment by MuYunyun** [comment]
@berserk5683 ant-design 官方给出的 demo 也是不支持 IE 的，以后也应该不会做这方面的支持。
