### ISSUE TITLE
怎么和后端的请求对接问题

### ISSUE THREAD

**Issue by zhouxinghui** [MuYunyun/reactSPA#23]
如果我用java开发  后端怎么和你的前端对接啊

**Comment by MuYunyun** [comment]
这和后端语言用什么没关系，这个问题换个问法就是如何进行前后端分离开发，那么最本质的是就是后端提供相应的服务，前端使用node作为网关层调用相应的服务并返回前端相应的 url。我司是直接用node调用dubbo服务的。

**Comment by zhouxinghui** [comment]
不懂啊  能否给个案例啊  我就是要做前后端分离  现在关键就是怎么调用后端的服务  能否给个详细点的例子啊~ @MuYunyun

**Comment by xulayen** [comment]
@zhouxinghui 就相当于前后端完全分离，如果你是做前端的。可以直接使用ajax调用你们的java服务，这时可能需要处理跨域的问题，前端后端处理都可以。但是你也可以在前端使用nodejs服务调用你的java服务，比较流行node框架可以使用类似express什么的。。。
