### ISSUE TITLE
menu的主题在切换的时候有一个动画，导致了动作不一。

### ISSUE THREAD

**Issue by wzn123w2** [MuYunyun/reactSPA#26]
在切换主题的时候会有的menu先变色 有的会后变色 这个怎么解决呢 ？

**Comment by MuYunyun** [comment]
@wzn123w2 请提供相应运行的环境，以及具体操作。

**Comment by wzn123w2** [comment]
就是您的项目直接运行的，另外在router。js的文件里会提示 <HashRouter> ignores the history prop. To use a custom history, use `import { Router }` instead of `import { HashRouter as Router }`.  把他的history属性删除掉就不会报了 ，但是有没有映像呢？

**Comment by MuYunyun** [comment]
@wzn123w2 我最初引用 createBrowserHistory 的目的是为了实现用户登录时跳转到主页面，不过现在项目中登入到主页面的过程只是页面的静态实现，所以去掉 history 属性没有影响的。
