### ISSUE TITLE
脚手架

### ISSUE THREAD

**Issue by niujianbo** [MuYunyun/reactSPA#27]
这个项目用的脚手架，然后eject了？还是webpack全是自己配的

**Comment by MuYunyun** [comment]
@niujianbo 在eject的基础上改的

**Comment by niujianbo** [comment]
看你commit 现在还在更新着呢？

**Comment by MuYunyun** [comment]
@niujianbo 是的，会进行优化和扩展

**Comment by beyondonly** [comment]
您好！我看了项目 ，但是里面的配置这块您是基于开源的产生还是自己写的

**Comment by beyondonly** [comment]
配置那块挺多，所以想了解一下

**Comment by beyondonly** [comment]
@MuYunyun  看到了 通eject生成后在修改的

**Comment by beyondonly** [comment]
export const todoList = handleActions({
  'ADD_TODO'(state, action) {
    return [
      ...state,
      todo(undefined, action.payload)
    ]
  },
  'TOGGLE_TODO'(state, action) {
    return state.map(t => todo(t, action.payload))
  },
  'DEL_TODO'(state, action) {
    return state.filter(t => t.id !== action.payload.id)
  }
}, todoListInit)

 'TOGGLE_TODO'(state, action) 
这种写法我看到挺诱惑的  是es6支持的？
@MuYunyun

**Comment by MuYunyun** [comment]
@beyondonly 是的，可以看以下三种写法的差异：
```js
var obj = {
	a(value) {
		return 1
	},
	b: function(value) {
		return 1
	},
	c: function c(value) {
		return 1
	}
}
```
![image](https://user-images.githubusercontent.com/19354791/33478875-ca7ecdc2-d6c5-11e7-9765-e136208264e1.png)
可看出 a(value) { return 1 } 的写法 和 function c(value) { return 1 } 的写法是相同的，即都是具名函数，而 b: function(value) {return 1} 是匿名函数
