### ISSUE TITLE
向大神咨询一个路由问题，小白一枚

### ISSUE THREAD

**Issue by Leous** [MuYunyun/reactSPA#31]
![image](https://user-images.githubusercontent.com/24190987/33822914-2f500c18-de94-11e7-9a37-7d7580c8d57a.png)
我是使用BrowserRouter写的路由，<Switch>标签下的两个<Route>中path="/"的那个必须放在第一位么？

若path="/"放在第一位，<Route path="/login" component={Login} />访问login时根本跳转不到登录页面，图中所截取的存放方式却可以实现，为什么？是我配路由的方式不对是么？

**Comment by MuYunyun** [comment]
#32
