### ISSUE TITLE
路由问题

### ISSUE THREAD

**Issue by Leous** [MuYunyun/reactSPA#32]
路由的设计思路是参照你的项目设计的，但是登录成功之后无法跳转到首页，页面显示一片空白，原因应该是没有进入container

![_20171211172042](https://user-images.githubusercontent.com/24190987/33823926-b0ce2da8-de97-11e7-9490-a8b8868697ae.png)
![image](https://user-images.githubusercontent.com/24190987/33823940-bc02811a-de97-11e7-8931-fdae5823b5af.png)

<Route>标签里的exact又不能去掉，去掉的话就全渲染了，有无法跳转到登录页面了

**Comment by Leous** [comment]
去掉exact属性后，进入了以下部分
![_20171211173746](https://user-images.githubusercontent.com/24190987/33824878-bbe8fcce-de9a-11e7-98c1-321f15a6a97e.png)

并没有进入登录页面<Route path="/login" component={Login} />，而是渲染出了头部和侧边栏部分
![_20171211174011](https://user-images.githubusercontent.com/24190987/33824883-bf2d6eba-de9a-11e7-8a23-0dc448e0903e.png)

**Comment by MuYunyun** [comment]
@Leous 有一个Redirect属性用来重定向，`location.hash === '#/' ? <Redirect to='/login' />`,[代码路径](https://github.com/MuYunyun/reactSPA/blob/443723785ec061e10054b964977376c819f2ef33/src/common/routes.js#L16)。
然后其实这个路由的写法有一个性能上的 bug，就是不管登入什么界面，登录界面都会被渲染(只是显示隐藏罢了)。最近在写其它东西，比较忙，这个问题有时间我会进行修复。也欢迎提出你的意见和想法。

**Comment by MuYunyun** [comment]
对 react-router 4.x 的一些探索:
为了支持 github 上展示该项目以及登入该项目时自动跳转到登入页，所以依然保持原来写法
```js
<HashRouter>
    <div>
      <Route path="/" component={Container} />
      <Route path="/login" component={Login} />
      {location.hash === '#/' ? <Redirect to='/login' /> : ''}
    </div>
  </HashRouter>
```
但是在正式项目中，为了保护页面安全性，以及提升性能，可以使用 [Switch](http://reacttraining.cn/web/api/Switch) 标签，因为它只会渲染最先匹配到的那个路由，写法如下：
```js
<Switch>
  <Route exec path="/" component={Container} />
  <Route exec path="/login" component={Login} />
</Switch>
```

**Comment by xulayen** [comment]
但是我使用http://localhost:3000/#/ 打开这个路由时，未命中任何路由。如果在container/content中加上
        <Route path="/" component={Index} />右边框架就会出现多个路由页面。

**Comment by xulayen** [comment]
<Route path="/storeList" component={Store} />

**Comment by MuYunyun** [comment]
@xulayen 
```js
location.hash === '#/' ? <Redirect to='/login' /> : ''
```
这句代码命中的 `#/` 是 `HashRouter` 提供的，真实项目的话可以用 React-router 4 提供的另外一个标签 [BrowserRouter](https://reacttraining.com/react-router/web/api/BrowserRouter);
然后 react-router 4 中提供了更高的自由性，
```js
<Route path="/" component={Index} />
```
Index 组件里包含了该项目的其他子组件

**Comment by lightforme** [comment]
hello，我也遇到了类似的路由的问题，
```
<Route path='/' component={Index} />
```
不写`exact`,可以访问到`Index`组件下的`<Route />`,但是同时访问`/login`，Index组件也会出来，写了`exact`，就访问不到`Index`组件下的`<Route />`了，请求这个应该怎么处理呢，还是本身就不应该这样处理，应该将`Index`组件的`<Route />`写成二级路由，例如：
```
<Route path='/home' component={Index}  />
// Index组件里
<Route path='/home/test' component={test} />
```
求指点

**Comment by lightforme** [comment]
好像找到方法了...打扰了
```
<Switch className="main">
            <Route path="/test" component={ Test} exact />
            <Route path="/" component={ Index} />
        </Switch>
```

**Comment by drx0811** [comment]
强制刷新页面路由会跳到index,
