### ISSUE TITLE
menu 模块

### ISSUE THREAD

**Issue by xulayen** [MuYunyun/reactSPA#36]
我在选择某个模块，比如#/album，重新刷新页面。页面还是#/album的页面，但是左侧的tab并没有选中

**Comment by MuYunyun** [comment]
https://github.com/MuYunyun/reactSPA/blob/1e7b0df9b3bfeaded234f0d048feb5fdb124d7b1/src/common/container/index.js#L56

@xulayen 可以修改 menu 模块中的 defaultOpenKeys 和 selectedKeys 达到你想要的效果
