### ISSUE TITLE
注册页面

### ISSUE THREAD

**Issue by xulayen** [MuYunyun/reactSPA#37]
我第一次打开输入错误的帐密点击按钮提示我“XXXX”，再次刷新页面会自动又提示我“XXXXX”

**Comment by MuYunyun** [comment]
可以参考这两条 issue
https://github.com/MuYunyun/reactSPA/issues/21，
https://github.com/MuYunyun/reactSPA/issues/32

**Comment by MuYunyun** [comment]
https://github.com/MuYunyun/reactSPA/issues/21
#32
之前已作出了解释，该项目是一个独立的前端项目，如果要模拟完整的项目流程，可以关注后续写的[网关项目](https://github.com/MuYunyun/gateway)
