### ISSUE TITLE
页面的分页机制

### ISSUE THREAD

**Issue by xulayen** [MuYunyun/reactSPA#39]
我看了一下这个页面的分页机制，实际上是进行内存分页，并不是使用异步加载分页机制。这里是有开关控制吗

**Comment by MuYunyun** [comment]
@xulayen 看得蛮仔细的~，这个项目因为调用了百度音乐的 api，看了一圈，发现它只有提供 100 条音乐的接口，所以项目中是一次性加载 100 条数据的。antd 的 table 组件还是蛮强大的，支持你所理解的 `内存分页` 以及 `异步加载分页机制`。具体的分页机制细节要看其源码了。

**Comment by MuYunyun** [comment]
@xulayen 另外提 issue 的时候最好把标题和描述分开，:smile:

**Comment by xulayen** [comment]
好的，这个分页框架蛮不错的，谢谢大神的回复。另外，这个项目的UI挺清爽的，我本人挺喜欢的，但是有一点就是多个tab打开在右侧始终只有一个tab。这个后续会进行升级更新吗？

**Comment by MuYunyun** [comment]
打开多个tab的时候，右侧显示的本来就是一个tab呀。
如果有好的想法欢迎提 pr，后续也会对项目进行其他方面的改造。

**Comment by xulayen** [comment]
你在实际工作中是使用内存分页还是 ajax异步分页呢？

**Comment by MuYunyun** [comment]
肯定是ajax异步分页的，不可能一次性返回给你上万条数据的

**Comment by xulayen** [comment]
在你这个基础上改改，试试看

**Comment by MuYunyun** [comment]
这个只是个前端项目，你要尝试 ajax 异步分页的话，可以在本地建个后台项目或者 mock 好数据来模拟，具体操作就是点击下一页按钮调用相应的 ajax 就行

**Comment by xulayen** [comment]
![image](https://user-images.githubusercontent.com/15044564/35374666-d9ca977c-01de-11e8-9e7e-ac23070c8887.png)
改这个函数就可以了吗

**Comment by MuYunyun** [comment]
不用改这个函数的，不过你可以自己尝试下，就是结合 redux 的那一套例子，我代码中也写了相关的demo,
过段时间会写个异步加载的 demo 吧，最近在做其他方面的优化

**Comment by xulayen** [comment]
试了一下，基于你的框架修改异步分页，没搞定，能更新一个demo 我看看么

**Comment by MuYunyun** [comment]
~年前时间比较紧张，你可以去看下 antd issue里寻求下帮助，另外建议学习下 redux 的流程，我在代码中给出了 todoList 的 demo，其实分页的写法和其是一样的。
