### ISSUE TITLE
SearchBar组件中的input类型疑问

### ISSUE THREAD

**Issue by xulayen** [MuYunyun/reactSPA#40]
当我使用 type='input'时，页面上的文本框只能输入一个字符，但是我看了源码好像并没有限制maxlength

``` js
{
            title: '歌曲名称',
            key: ['songName'],
            type: 'input',
 }
```

![image](https://user-images.githubusercontent.com/15044564/35316550-3c4acc5a-010d-11e8-9d87-9dbfa2d5c6f6.png)

**Comment by MuYunyun** [comment]
key 的格式设置错了，
https://github.com/MuYunyun/reactSPA/blob/541795e656e69a8dd525f46d6365e5f58af9b4f6/src/common/components/searchbar/index.js#L103
