### ISSUE TITLE
压缩打包实践

### ISSUE THREAD

**Issue by yurizhang** [MuYunyun/reactSPA#43]
能还配置优化或是分块打包，目前打包出来文件太大了

**Comment by MuYunyun** [comment]
针对该项目的文件打包太大，可以采用 `code-splitting`
```
you can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```
这个星期会解决这个问题~

**Comment by MuYunyun** [comment]
* 对模块结合 babel 进行[按需加载](https://github.com/demos-platform/onDemandLoading);
* 测试 day.js 替代 moment.js. 使用[按需加载](https://github.com/jmblog/how-to-optimize-momentjs-with-webpack)，其实相差不大;

```
  677.54 KB   build/static/js/vendor.6bcbf6d0.chunk.js
  98.18 KB     build/static/js/main.cfbe1829.js
  8.2 KB         build/static/css/0.css
```

待测试：You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
