### ISSUE TITLE
你好，请问网站7天访问量的数据是怎么获得的

### ISSUE THREAD

**Issue by bufudanqing** [MuYunyun/reactSPA#44]
1. 首页右下角的流量模块数据有借助其他工具吗？
2. 这个链接 http://muyunyun.cn/posts/9bfbdbf4/ 页面最下方的总访问人次和总访问量数据是怎么统计的呢？
谢谢:)

**Comment by Somefuture** [comment]
用echarts生成了图表，源码里的访问人数是静态的。

**Comment by bufudanqing** [comment]
好的，谢谢，我以为是实际的访问数据
