### ISSUE TITLE
此项目不支持IE11？

### ISSUE THREAD

**Issue by honghaozhilian** [MuYunyun/reactSPA#45]
在IE11中打开报错，请问这个项目是不支持IE11的吗

**Comment by honghaozhilian** [comment]
打扰了，问题已经找到了，antd要支持IE需要加入polyfill,antd的官网有说明兼容问题

**Comment by comid** [comment]
> 打扰了，问题已经找到了，antd要支持IE需要加入polyfill,antd的官网有说明兼容问题

你的问题解决了么
