### ISSUE TITLE
代理怎么设置

### ISSUE THREAD

**Issue by liaoyuecai** [MuYunyun/reactSPA#47]
我在webpack.config.dev.js上面设置的代理好像没什么用
devServer: {
        proxy: {
            '/api': {
                target: 'http://localhost:4000/application',
                secure: false
            }
        }
    }

加了上面一段还是没生效

**Comment by MuYunyun** [comment]
可以在 package.json 文件里加上 "proxy": "xxx" 试试

https://github.com/MuYunyun/reactSPA/blob/cbcd9fd1d1022ff90c11b5ede0ab72e760b3cec2/scripts/start.js#L55

**Comment by liaoyuecai** [comment]
可以的  谢谢
