### ISSUE TITLE
react 性能优化实践

### ISSUE THREAD

**Issue by MuYunyun** [MuYunyun/reactSPA#54]
* 使用 React Profiler，[Introducing the React Profiler](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html)，有了 React Profiler 后，优化性能会变得直观，比如各个组件渲染的时间，也可以观察组件是否进行了无用的渲染。

* 使用 PureComponent

* 使用不可变数据，[在 react 使用 immutable.js 的优势](https://github.com/MuYunyun/blog/blob/master/BasicSkill/%E6%A1%86%E6%9E%B6%E7%AF%87/%E5%9C%A8react%E4%BD%BF%E7%94%A8immutable%E6%95%B0%E6%8D%AE%E7%9A%84%E4%BC%98%E5%8A%BF.md)

* 重构与良好设计，[性能优化实践之 —— 使用 why-did-you-update](https://github.com/demos-platform/why-did-you-update)

* babel 插件的运用，[plugin-transform-react-constant-elements](https://babeljs.io/docs/en/next/babel-plugin-transform-react-constant-elements.html), 它的原理是提升一些不会变的 React 元素的作用域。从而避免重复多次实例化 ReactElement。用于生产环境，开发环境会造成调试困扰。

**Comment by snakeUni** [comment]
汝之秀，吾何时能及
