### ISSUE TITLE
浏览器兼容问题

### ISSUE THREAD

**Issue by comid** [MuYunyun/reactSPA#58]
如题，IE系列无法兼容啊

**Comment by MuYunyun** [comment]
报错原因能提供下么~

**Comment by comid** [comment]
我提交不上，你自己改改吧。代码在下面
npm install babel-polyfill
webpack.config.dev中：
 entry: [
        'babel-polyfill', // 该行会导致编译后文件变大，但是能兼容IE11，取舍使用
        `${require.resolve('webpack-dev-server/client')}?/`,
        require.resolve('webpack/hot/dev-server'),
        require.resolve('react-error-overlay'), // 开发报错，将导致启动不了
        paths.appIndexJs,
    ],

webpack.config.prod中：
   entry: {
         // IndexJs: paths.appIndexJs,
         IndexJs: ['babel-polyfill', paths.appIndexJs],
    },
