### ISSUE TITLE
npm install 或者 yarn install 下载不了包。。。是工程有问题吗

### ISSUE THREAD

**Issue by shiwei1019** [MuYunyun/reactSPA#69]
What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

What is the expected behavior?

**Comment by MuYunyun** [comment]
能否提供相关截图?

**Comment by shiwei1019** [comment]
![2020-05-31_125718](https://user-images.githubusercontent.com/44516150/83344843-cbc1d880-a33e-11ea-9bcc-381820a170ad.png)
![2020-05-31_125803](https://user-images.githubusercontent.com/44516150/83344845-ccf30580-a33e-11ea-9e4c-0286280ae498.png)

**Comment by shiwei1019** [comment]
npm ERR! path C:\Users\XSW\Desktop\reactSPA-master\node_modules\.staging\echarts-cb9691e0\dist\echarts-en.js.map
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\XSW\Desktop\reactSPA-master\node_modules\.staging\echarts-cb9691e0\dist\echarts-en.js.map'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Users\XSW\Desktop\reactSPA-master\node_modules\.staging\echarts-cb9691e0\dist\echarts-en.js.map']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\XSW\Desktop\reactSPA-master\node_modules\.staging\echarts-cb9691e0\dist\echarts-en.js.map'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\Users\\XSW\\Desktop\\reactSPA-master\\node_modules\\.staging\\echarts-cb9691e0\\dist\\echarts-en.js.map' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\Users\\XSW\\Desktop\\reactSPA-master\\node_modules\\.staging\\echarts-cb9691e0\\dist\\echarts-en.js.map\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\Users\\XSW\\Desktop\\reactSPA-master\\node_modules\\.staging\\echarts-cb9691e0\\dist\\echarts-en.js.map',
npm ERR!   parent: 'reactSPA-master' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XSW\AppData\Roaming\npm-cache\_logs\2020-05-31T04_52_33_664Z-debug.log

**Comment by MuYunyun** [comment]
可以 yarn cache clean 然后再 yarn 试试, 我本地 yarn 后 yarn start 是能启动的。
