### ISSUE TITLE
路由上那个#号一直去不掉

### ISSUE THREAD

**Issue by liaoyuecai** [MuYunyun/reactSPA#70]
我把代码改成了这样  还是一直有#号
![image](https://user-images.githubusercontent.com/33653091/94365787-337a0b80-0106-11eb-8372-1dff3a13b043.png)

**Comment by MuYunyun** [comment]
> 我把代码改成了这样 还是一直有#号
> ![image](https://user-images.githubusercontent.com/33653091/94365787-337a0b80-0106-11eb-8372-1dff3a13b043.png)

使用 history 路由需要用 nginx 处理一下文件路径。详细可以见[这里](https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing)
